### ISSUE TITLE
Outstanding Features to Implement

### ISSUE THREAD

**Issue by clloyd** [guardian/tagmanager#52]
## Required to replace R2

- [x] Merge Tag - #72 
- [x] Delete Tag - #72
- [x] Section Editor - #57 
 - [x] Section Creation
 - [x] Update Section Discriminator on editionalisation - #89
- [x] Microsite Manager
- [x] Audit/Status Screen
- [x] Mapping Manager - #54
- [x] Permissions
  - [x] Add Support for Permissions - #55 
  - [x] Add Super Admin and admin levels #66 
  - [x] Limit tag creation, update and deletion #79 
- [x] Migrate remaining tag types
  - [x] Blog - https://github.com/guardian/tag-migrator/pull/10
  - [x] Publication
  - [x] Newspaper - https://github.com/guardian/tag-migrator/pull/11
  - [x] Newspaper Book - https://github.com/guardian/tag-migrator/pull/11
  - [x] Content Type
  - [x] Blog's not being syndicated before could now be syndicated as series? 
- [x] Flex changes around Tag indexing
  - [x] TagManager/Flex communication regarding external references updates. (Tag reindex from flex)  (https://github.com/guardian/flexible-content/pull/2254 and https://github.com/guardian/flexible-feeds/pull/9)
  - [x] Trigger reindex on ExternalReferences Change
- [x] Flex changes to replace Tag API ( https://github.com/guardian/tagmanager/pull/60 and https://github.com/guardian/flexible-content/pull/2252)
- [x] Tags XML for InCopy - https://github.com/guardian/tagmanager/pull/58
  - [x] Update the exported XML Model - https://github.com/guardian/tagmanager/pull/69
  - [x] Add additional routes for inCopy (https://github.com/guardian/tagmanager/pull/75)
  - [ ] Stop XML endpoints from timing out (20MB of xml) (inprogress @hmgibson23)
- [x] Pluto?
- [x] PathManager Communication Issues in CODE (and presumably PROD)  - #86
- [x] CAPI
 - [x] Reindex Endpoints for Tags #73
 - [x] Reindex Endpoints for Sections #84 
 - [x] Produce Library from thrift #63
- [x] Panda ReAuth #106
- [x] Into Production!!  (inprogress @clloyd)
 - [x] Domain (Requested...)
 - [x] Create Dynamo Tables
 - [x] Create SQS Queues
 - [x] Relevant Backups
 - [x] Benchmark current TagApi from flex demand and ensure can meet it
